### ISSUE TITLE
Error in Call Composite/Join Existing Call

### ISSUE THREAD

**Issue by deepakhariharan** [Azure/communication-ui-library#2344]
**Describe the bug; what happened?** 
The bug is in CallComposite/Join Existing Call. 
Entered 'User Identify for user'
Entered 'Valid token for user'
Entered 'Call locator (ACS group ID or Teams meeting link)' Entered Teams Meeting Link

I got the Bug
'Unable to join Meeting. Invalid Link.'

**What are the steps to reproduce the issue?**
Enter'User Identify for user'
Enter 'Valid token for user'
Enter 'Call locator (ACS group ID or Teams meeting link)' Enter Teams Meeting Link

**What behavior did you expect?**
Was Expecting to connect with Teams Meeting with my Partner
**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/17702613/190317733-0202292b-13e4-4b8e-acb0-58e5e4fee30d.png)

**In what environment did you see the issue?**
Windows 10 Desktop Environment

- `@azure/communication-react` npm package version (if applicable): [e.g. 1.3.0]
- `@azure/communication-calling` npm package version (if applicable): [e.g. 1.5.4-beta.1]
- `@azure/communication-chat` npm package version (if applicable): [e.g. 1.2.2]

- OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
Windows 10 
- Browser: [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
Google Chrome
- Browser Version: [e.g. 1.8.0]

**Is there any additional information?**

**Comment by prprabhu-ms** [comment]
The error banner suggets that the meeting link you provided was invalid. Could you post the meeting link you used? (Perhaps redact any UID-like parts of the link before posting here)

**Comment by deepakhariharan** [comment]
@prprabhu-ms  This is the Link
https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZmE3NDI1YWQtYzRhOS00YjFiLTgzYjMtYWI0M2VhYjI4MTU2%40thread.v2/0?context=%7b%22Tid%22%3a%2236da45f1-dd2c-4d1f-af13-5abe46b99921%22%2c%22Oid%22%3a%2221434d69-289a-4ef8-af03-c67b497ff28b%22%7d&gt;

**Comment by prprabhu-ms** [comment]
Not sure if the trailing `>` was part of the link you provided, but that isn't part of the meeting link.

**Comment by deepakhariharan** [comment]
No > is not a part of the Link here is the Link
https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZmE3NDI1YWQtYzRhOS00YjFiLTgzYjMtYWI0M2VhYjI4MTU2%40thread.v2/0?context=%7b%22Tid%22%3a%2236da45f1-dd2c-4d1f-af13-5abe46b99921%22%2c%22Oid%22%3a%2221434d69-289a-4ef8-af03-c67b497ff28b%22%7d

**Comment by deepakhariharan** [comment]
@prprabhu-ms 
I entered a new Teams Link 
https://teams.live.com/meet/9582750218213
The Error has changed this is the new Error I am getting.

![image](https://user-images.githubusercontent.com/17702613/190601188-ac4b5e0c-f3b1-4f3e-860f-bc3ad9f06a00.png)

**Comment by edwardlee-msft** [comment]
Hi @deepakhariharan,

Can you please provide a screen capture of the console log in the inspection tool? From what I initially see, the Teams link you provided does not seem to be malformed. 
Can you also please confirm if the ACS user token is valid and not expired? (Additionally, please watch out for any trailing white space when pasting in the token and userId).
![image](https://user-images.githubusercontent.com/97130533/190697009-9cbbb0de-2d36-4efd-ad4c-f5b4d59cdad3.png)

**Comment by deepakhariharan** [comment]
**This is the Console Log I am getting, I am using a Valid Token and User ID.**

main.91d076f289613783016c.manager.bundle.js:1 This Storybook was compiled for @azure/communication-react version 1.3.1-beta.1
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
 Importing from '@storybook/addon-docs/blocks' is deprecated, import directly from '@storybook/addon-docs' instead:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-scoped-blocks-imports
deprecated @ vendors~main.2011f6e4.iframe.bundle.js:6
 `argType.defaultValue` is deprecated and will be removed in Storybook 7.0.

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-longer-inferring-default-values-of-args
deprecated @ vendors~main.2011f6e4.iframe.bundle.js:6
vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2  manager  received storySpecified but was unable to determine the source of the event
error @ vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2
vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2  manager  received currentStoryWasSet but was unable to determine the source of the event
error @ vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2
vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2  manager  received storyRenderPhaseChanged but was unable to determine the source of the event
error @ vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2
vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2  manager  received setGlobals but was unable to determine the source of the event
error @ vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2
vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2 Some icons were re-registered. Applications should only call registerIcons for any given icon once. Redefining what an icon is may have unintended consequences. Duplicates include: 
GlobalNavButton, ChevronDown, ChevronUp, Edit, Add, Cancel, More, Settings, Mail, Filter (+ 16199 more)
warn @ vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
vendors~main.2011f6e4.iframe.bundle.js:6 Importing from '@storybook/addon-docs/blocks' is deprecated, import directly from '@storybook/addon-docs' instead:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-scoped-blocks-imports
deprecated @ vendors~main.2011f6e4.iframe.bundle.js:6
vendors~main.2011f6e4.iframe.bundle.js:6 `argType.defaultValue` is deprecated and will be removed in Storybook 7.0.

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-longer-inferring-default-values-of-args
deprecated @ vendors~main.2011f6e4.iframe.bundle.js:6
vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2 Some icons were re-registered. Applications should only call registerIcons for any given icon once. Redefining what an icon is may have unintended consequences. Duplicates include: 
GlobalNavButton, ChevronDown, ChevronUp, Edit, Add, Cancel, More, Settings, Mail, Filter (+ 5393 more)
warn @ vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2
vendors~main.2011f6e4.iframe.bundle.js:6 Props doc block has been renamed to ArgsTable.

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#previewprops-renamed
deprecated @ vendors~main.2011f6e4.iframe.bundle.js:6
vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2 Some icons were re-registered. Applications should only call registerIcons for any given icon once. Redefining what an icon is may have unintended consequences. Duplicates include: 
GlobalNavButton, ChevronDown, ChevronUp, Edit, Add, Cancel, More, Settings, Mail, Filter (+ 7194 more)
warn @ vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2
vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2 Omitted potentially unsafe URL args.

More info: https://storybook.js.org/docs/react/writing-stories/args#setting-args-through-the-url
warn @ vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2
2vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2 Some icons were re-registered. Applications should only call registerIcons for any given icon once. Redefining what an icon is may have unintended consequences. Duplicates include: 
GlobalNavButton, ChevronDown, ChevronUp, Edit, Add, Cancel, More, Settings, Mail, Filter (+ 3592 more)
warn @ vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2
2vendors~main.2011f6e4.iframe.bundle.js:2 ECS - Config fetch complete
vendors~main.2011f6e4.iframe.bundle.js:2 ECS - Delaying User config fetch until we have a valid SkypeToken
vendors~main.2011f6e4.iframe.bundle.js:2 ECS - Config fetch complete
vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2 Some icons were re-registered. Applications should only call registerIcons for any given icon once. Redefining what an icon is may have unintended consequences. Duplicates include: 
GlobalNavButton, ChevronDown, ChevronUp, Edit, Add, Cancel, More, Settings, Mail, Filter (+ 3592 more)
warn @ vendors~main.d55b03c4cbbfdacdf41e.manager.bundle.js:2
vendors~main.2011f6e4.iframe.bundle.js:2 Some icons were re-registered. Applications should only call registerIcons for any given icon once. Redefining what an icon is may have unintended consequences. Duplicates include: 
ChatMessageOptions, ControlButtonCameraOff, ControlButtonCameraOn, ControlButtonEndCall, ControlButtonMicOff, ControlButtonMicOn, ControlButtonOptions, ControlButtonParticipants, ControlButtonScreenShareStart, ControlButtonScreenShareStop (+ 41 more)
warn @ vendors~main.2011f6e4.iframe.bundle.js:2
vendors~main.2011f6e4.iframe.bundle.js:6 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 stateChanged listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (https://azure.github.io/communication-ui-library/vendors~main.2011f6e4.iframe.bundle.js:6:1931394)
    at EventEmitter.addListener (https://azure.github.io/communication-ui-library/vendors~main.2011f6e4.iframe.bundle.js:6:1934965)
    at CallContext.onStateChange (https://azure.github.io/communication-ui-library/main.4ba1cb59.iframe.bundle.js:1:928253)
    at AzureCommunicationCallAdapter.onStateChange (https://azure.github.io/communication-ui-library/main.4ba1cb59.iframe.bundle.js:1:952314)
    at https://azure.github.io/communication-ui-library/main.4ba1cb59.iframe.bundle.js:1:982250
    at Ii (https://azure.github.io/communication-ui-library/vendors~main.2011f6e4.iframe.bundle.js:6:2388230)
    at Vj (https://azure.github.io/communication-ui-library/vendors~main.2011f6e4.iframe.bundle.js:6:2406963)
    at exports.unstable_runWithPriority (https://azure.github.io/communication-ui-library/vendors~main.2011f6e4.iframe.bundle.js:6:2480744)
    at cg (https://azure.github.io/communication-ui-library/vendors~main.2011f6e4.iframe.bundle.js:6:2350186)
    at Dj (https://azure.github.io/communication-ui-library/vendors~main.2011f6e4.iframe.bundle.js:6:2406725)
ProcessEmitWarning @ vendors~main.2011f6e4.iframe.bundle.js:6
api.flightproxy.skype.com/api/v2/cpconv:1          Failed to load resource: the server responded with a status of 400 ()

**Comment by deepakhariharan** [comment]
@edwardlee-msft 
This is the screen shot of the console error.

![image](https://user-images.githubusercontent.com/17702613/190842940-bf224ec7-1916-4ad9-a7a6-86880cc7a8a7.png)

**Comment by anjulgarg** [comment]
Hi @deepakhariharan 
Any update on this?
Were you able to make it work?

**Comment by prprabhu-ms** [comment]
Closing due to inactivity.

I was unable to reproduce this issue myself, so if we do see it again, it'd be great to get some more insight into how we're getting the composite into this weird state.
