### ISSUE TITLE
Getting an error using the CallWihChatComposite with an existing thread id and a generated group id

### ISSUE THREAD

**Issue by jorgecolon413** [Azure/communication-ui-library#2692]
I'm currently trying to use the CallWithChatComposite demo in the UI Library and one of the options for a locator other than a Teams meeting link is a composition of thread id and group id. 

This is the error that the demo throws:
```
Uncaught (in promise) CallError: CallClient.createCallAgent: Failed to create call agent, call agent for this ACS Id already exists
    at toCallError (main.081f3dbe.iframe.bundle.js:1:252530)
    at _callee$ (main.081f3dbe.iframe.bundle.js:1:251751)
    at tryCatch (vendors~main.e1ece266.iframe.bundle.js:6:2462410)
    at Generator.invoke [as _invoke] (vendors~main.e1ece266.iframe.bundle.js:6:2462033)
    at Generator.throw (vendors~main.e1ece266.iframe.bundle.js:6:2463185)
    at CallContext_asyncGeneratorStep (main.081f3dbe.iframe.bundle.js:1:234234)
    at _throw (main.081f3dbe.iframe.bundle.js:1:234645)
```

I'm trying to use an existing thread Id and a generated group Id for the locator in this manner:
```
19:Ei_vQErHBQe7DArbUuqR0Jubw_hx8xiXuFZelLxIxzo1@thread.v2:6fef0010-a196-11ed-a8fc-0242ac120002
```
Questions: 
1. Is it possible to use this CallWithChatComposite in this manner ? 
2. How am I supposed to dynamically generate this thread Id and group Id for this composite without using the Teams meeting link?
3. Do I have to Join the two Id in some way ?

Thanks for your time.

**Comment by jorgecolon413** [comment]
I'm using react as framework for this components.
This is what I'm trying to do at the moment to generate a locator:
```
import { useState, useRef } from 'react';
import { v4 as uuidv4 } from 'uuid';

const joinThread = async (props) => {
    const [locator, setLocator] = useState('');
    const groupId = useRef(uuidv4());

    const headers = {
        "Content-Type": "application/json",
        Authorization: `Bearer ${props.userToken}`
    };
    const body = JSON.stringify({
        threadId: props.threadId,
        groupId: groupId.current
    });
    try {
        const response = await fetch(`${props.endpoint}threads/join`, {
            method: "POST",
            headers,
            body
        });
        if (!response.ok) {
            throw new Error(`Error joining chat thread: ${response.statusText}`);
        }
        console.log("Successfully joined chat thread.");
        setLocator(`${props.threadId}:${groupId.current}`);
        return { locator };

    } catch (error) {
        console.error(error.message);
    }
};

export default joinThread;
```

**Comment by PorterNan** [comment]
Hi, thanks for opening the issue.
Looks like there are 2 questions according to your description:

1. From the error message you saw, it seems like you are creating more than 1 call agent in the window, which might be caused by some memorization problem, would you like to share your code piece how you create the call agent?

2. For supporting groupId + threadId, yes, we support that, if you look at locator type we are accepting:
![image](https://user-images.githubusercontent.com/11863655/215898475-54ac5702-0fcb-4374-bbc9-e49f732597e1.png)

you can actually provide a CallAndChatLocator then provide your groupid+threadid there

Please lemme know if you have more questions when using this locator

**Comment by jorgecolon413** [comment]
The error was being thrown by the "Join Teams Meeting" from the ```CallWithChatComposite``` demo at: https://azure.github.io/communication-ui-library/?path=/story/composites-call-with-chat-jointeamsmeeting--join-teams-meeting 

I tried replicating the error but didn't get the same error using the same credentials as before. At the moment, I'm able to render the ```CallWithChatComposite``` but after clicking the start button, it throws the following error:
```
vendors~main.e1ece266.iframe.bundle.js:6 Uncaught CallError: CallAgent.join: Invalid meeting link
    at toCallError (main.081f3dbe.iframe.bundle.js:1:252530)
    at Proxy.<anonymous> (main.081f3dbe.iframe.bundle.js:1:252187)
    at AzureCommunicationCallAdapter._joinCall (main.081f3dbe.iframe.bundle.js:1:1026363)
    at main.081f3dbe.iframe.bundle.js:1:1026164
    at AzureCommunicationCallAdapter.teeErrorToEventEmitter (main.081f3dbe.iframe.bundle.js:1:1044376)
    at AzureCommunicationCallAdapter.joinCall (main.081f3dbe.iframe.bundle.js:1:1025664)
    at AzureCommunicationCallWithChatAdapter.joinCall (main.081f3dbe.iframe.bundle.js:1:1205847)
    at CallWithChatBackedCallAdapter.joinCall (main.081f3dbe.iframe.bundle.js:1:1141749)
    at Object.startCallHandler [as onClick] (main.081f3dbe.iframe.bundle.js:1:995692)
    at BaseButton._this._onClick (vendors~main.e1ece266.iframe.bundle.js:2:5327779)
```
which indicates that this demo only expect a Teams Meeting Link. I did this test because I'm trying to use the composite on my react app in this way:
```
const VideoComponent = (props) => {
    // A well-formed token is required to initialize the chat and calling adapters.        

    const { locator } = useJoinVideoChat(props);   

    const credential = useMemo(() => {
        try {
            return new AzureCommunicationTokenCredential(props.userToken);
        } catch {
            console.error('Failed to construct token credential');
            return undefined;
        }
    }, [props.userToken]);   

    // Memoize arguments to `useAzureCommunicationChatAdapter` so that
    // a new adapter is only created when an argument change              
    const callAdapterArgs = useMemo(
        () => ({
            endpoint: props.endpoint,
            userId: fromFlatCommunicationIdentifier(props.userId),
            displayName: props.displayName,
            credential,        
            locator: locator           
        }),
        [props.endpoint, props.userId, props.displayName, credential, locator]
    ); 

    const callAdapter = useAzureCommunicationCallWithChatAdapter(callAdapterArgs);

    if (!!callAdapter) { 
        
        return (
            <div style={{ height: '80vh', display: 'flex' }}>
                <div>
                    <CallWithChatComposite  adapter={callAdapter} />
                </div>
            </div>
        );
    }
    if (credential === undefined) {
        return <h3>Failed to construct credential. Provided token is malformed.</h3>;
    }
    return <h3>Initializing...</h3>;
}

export default VideoComponent;
```
But I'm not sure how to create the locator using an existing thread Id and a generated group Id. At the demo I'm using this locator: 
```
19:Ei_vQErHBQe7DArbUuqR0Jubw_hx8xiXuFZelLxIxzo1@thread.v2:6fef0010-a196-11ed-a8fc-0242ac120002
```
If I would dynamically create this locator, I would pass the thread Id as part of props to the ```useJoinVideoChat();``` function  and generate the group Id with ```useRef(uuidv4());``` and join them in this way  ```{`${props.threadId}:${groupId.current}`} ``` to return it from this function like this: 
```const { locator } = useJoinVideoChat(props);  ```

Is this how is intended to be dynamically created ? 
Asking because I didn't manage to found good documentation on how to implement this Composite with that kind of locator.

**Comment by PorterNan** [comment]
You could check this doc for creating callLocator with threadId and groupId:
https://azure.github.io/communication-ui-library/iframe.html?viewMode=docs&id=composites-call-with-chat-jointeamsmeeting--join-teams-meeting#prerequisites

Replicate a "fake" meeting link might work, but not by designed and fully supported by our adapter

One thing need some awareness is you might need to keep the reference of your locator (and all the other parameter of useAzureCommunicationCallWithChatAdapter to be the same), otherwise it will trigger the re-render of the hook and create agent for more than one time

**Comment by jorgecolon413** [comment]
Is there a demo where I can test this type of locator other then with my own implementation? 
Seeing the documentation previously mentioned and I don't see how it is supposed to send the locator to the ```CallWithChatComposite```.

I can see below the ```prerequisites``` how to generate the thread Id using the ```ChatClient``` object and the group Id using a GUID generator and then returning each one of the Id's. But there is no demonstration on how to pass both as a ```locator``` to the ```CallWithChatComposite``` since the demo only shows ho to use the ```TeamsMeetingLink```. 

Is it supposed to work with the concat of both Id's or in a JSON format ? 
Am I supposed to use a Locator converter, similar to ```fromFlatCommunicationIdentifier``` ?

**Comment by jorgecolon413** [comment]
Trying to generate the locator by concatenating an existing thread Id and a randomly generated group Id with this format 
``` `${threadId}:${groupId}` ``` in the following block of code:
```
const VideoComponent = (props) => {
    // A well-formed token is required to initialize the chat and calling adapters.        

    const groupId  = {groupId: uuidv4()};



    const credential = useMemo(() => {
        try {
            return new AzureCommunicationTokenCredential(props.userToken);
        } catch {
            console.error('Failed to construct token credential');
            return undefined;
        }
    }, [props.userToken]);

    // Memoize arguments to `useAzureCommunicationChatAdapter` so that
    // a new adapter is only created when an argument change              
    const callAdapterArgs = useMemo(
        () => ({
            endpoint: props.endpoint,
            userId: fromFlatCommunicationIdentifier(props.userId),
            displayName: props.displayName,
            credential,
            locator: `${props.threadId}:${groupId.groupId}`
        }),
        [props.endpoint, props.userId, props.displayName, credential, props.threadId]
    );

    const callAdapter = useAzureCommunicationCallWithChatAdapter(callAdapterArgs);

    if (!!callAdapter) {

        return (
            <div style={{ height: '70vh', display: 'flex' }}>
                <div>
                    <CallWithChatComposite adapter={callAdapter} />
                </div>
            </div>
        );
    }
    if (credential === undefined) {
        return <h3>Failed to construct credential. Provided token is malformed.</h3>;
    }
    return <h3>Initializing...</h3>;

}

export default VideoComponent;
```

Resulted in the following error when trying to initiate the CallWithChatComposite:

```
index.js:1 Fetch API cannot load thread.v2:69b223a5-8bcc-475d-8d22-c2b016588777. URL scheme "thread.v2" is not supported.
```
And this other error:
```
Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'meetingLink' in 19:Ei_vQErHBQe7DArbUuqR0Jubw_hx8xiXuFZelLxIxzo1@thread.v2:69b223a5-8bcc-475d-8d22-c2b016588777
    at isTeamsMeetingLinkLocator (AzureCommunicationCallWithChatAdapter.ts:703:1)
    at AzureCommunicationCallWithChatAdapter.ts:551:1
    at Generator.next (<anonymous>)
    at AzureCommunicationCallWithChatAdapter.ts:2:1
    at new Promise (<anonymous>)
    at push../node_modules/@azure/communication-react/dist/dist-esm/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.js.__awaiter (AzureCommunicationCallWithChatAdapter.ts:2:1)
    at createAzureCommunicationCallWithChatAdapter (AzureCommunicationCallWithChatAdapter.ts:550:1)
    at AzureCommunicationCallWithChatAdapter.ts:624:1
    at Generator.next (<anonymous>)
    at AzureCommunicationCallWithChatAdapter.ts:2:1
    at new Promise (<anonymous>)
    at push../node_modules/@azure/communication-react/dist/dist-esm/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.js.__awaiter (AzureCommunicationCallWithChatAdapter.ts:2:1)
    at AzureCommunicationCallWithChatAdapter.ts:609:1
    at AzureCommunicationCallWithChatAdapter.ts:638:1
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at react-dom.development.js:23324:1
    at workLoop (scheduler.development.js:417:1)
    at flushWork (scheduler.development.js:390:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157:1)
isTeamsMeetingLinkLocator @ AzureCommunicationCallWithChatAdapter.ts:703
(anonymous) @ AzureCommunicationCallWithChatAdapter.ts:551
(anonymous) @ AzureCommunicationCallWithChatAdapter.ts:2
push../node_modules/@azure/communication-react/dist/dist-esm/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.js.__awaiter @ AzureCommunicationCallWithChatAdapter.ts:2
createAzureCommunicationCallWithChatAdapter @ AzureCommunicationCallWithChatAdapter.ts:550
(anonymous) @ AzureCommunicationCallWithChatAdapter.ts:624
(anonymous) @ AzureCommunicationCallWithChatAdapter.ts:2
push../node_modules/@azure/communication-react/dist/dist-esm/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.js.__awaiter @ AzureCommunicationCallWithChatAdapter.ts:2
(anonymous) @ AzureCommunicationCallWithChatAdapter.ts:609
(anonymous) @ AzureCommunicationCallWithChatAdapter.ts:638
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
Promise.then (async)
step @ AzureCommunicationCallWithChatAdapter.ts:2
(anonymous) @ AzureCommunicationCallWithChatAdapter.ts:2
push../node_modules/@azure/communication-react/dist/dist-esm/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.js.__awaiter @ AzureCommunicationCallWithChatAdapter.ts:2
(anonymous) @ AzureCommunicationCallWithChatAdapter.ts:609
(anonymous) @ AzureCommunicationCallWithChatAdapter.ts:638
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
```

**Comment by PorterNan** [comment]
> Is there a demo where I can test this type of locator other then with my own implementation? Seeing the documentation previously mentioned and I don't see how it is supposed to send the locator to the `CallWithChatComposite`.
> 
> I can see below the `prerequisites` how to generate the thread Id using the `ChatClient` object and the group Id using a GUID generator and then returning each one of the Id's. But there is no demonstration on how to pass both as a `locator` to the `CallWithChatComposite` since the demo only shows how to use the `TeamsMeetingLink`.
> 
> Is it supposed to work with the concat of both Id's or in a JSON format ? Am I supposed to use a Locator converter, similar to `fromFlatCommunicationIdentifier` ?

![image](https://user-images.githubusercontent.com/11863655/217057349-9d7fd211-5cac-4ed3-80a0-1e1ed229fe77.png)

Once you get this object of this return value, just go ahead and pass it as locator, then it should be running well - one thing need to be aware is this object should be also memorized (useMemo this object)

(BTW, If you are able to code it in typescript you can easily figure out what type would be acceptable to those parameters)

**Comment by jorgecolon413** [comment]
Did some changes to my code trying to cover your last comment but its seems the ```CallWithChatComposite``` still expects a ```meetingLinks``` as described by this most recent error:
```
Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'meetingLink' in 1d3101f0-a657-11ed-b2f1-31cb080208a9
    at new AzureCommunicationCallAdapter (AzureCommunicationCallAdapter.ts:158:1)
    at AzureCommunicationCallAdapter.ts:726:1
    at Generator.next (<anonymous>)
    at fulfilled (Strings.tsx:2:1)
AzureCommunicationCallAdapter @ AzureCommunicationCallAdapter.ts:158
(anonymous) @ AzureCommunicationCallAdapter.ts:726
fulfilled @ Strings.tsx:2
Promise.then (async)
step @ AzureCommunicationCallWithChatAdapter.ts:2
(anonymous) @ AzureCommunicationCallWithChatAdapter.ts:2
push../node_modules/@azure/communication-react/dist/dist-esm/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.js.__awaiter @ AzureCommunicationCallWithChatAdapter.ts:2
(anonymous) @ AzureCommunicationCallWithChatAdapter.ts:609
(anonymous) @ AzureCommunicationCallWithChatAdapter.ts:638
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
```
Here is my code following your last feedback:
```
const VideoComponent = (props) => {
    // A well-formed token is required to initialize the chat and calling adapters.        

    //const groupId  = {groupId: uuidv4()};

    const locator = useMemo(() => {
        return {
            callLocator: createGUID() ,
            chatThreadId:  props.threadId 
          };
    }, [props.threadId]) 


    const credential = useMemo(() => {
        try {
            return new AzureCommunicationTokenCredential(props.userToken);
        } catch {
            console.error('Failed to construct token credential');
            return undefined;
        }
    }, [props.userToken]);

    // Memoize arguments to `useAzureCommunicationChatAdapter` so that
    // a new adapter is only created when an argument change              
    const callAdapterArgs = useMemo(
        () => ({
            endpoint: props.endpoint,
            userId: fromFlatCommunicationIdentifier(props.userId),
            displayName: props.displayName,
            credential,
            locator
        }),
        [props.endpoint, props.userId, props.displayName, credential, locator]
    );

    const callAdapter = useAzureCommunicationCallWithChatAdapter(callAdapterArgs);

    if (!!callAdapter) {

        return (
            <div style={{ height: '70vh', display: 'flex' }}>
                <div>
                    <CallWithChatComposite adapter={callAdapter} />
                </div>
            </div>
        );
    }
    if (credential === undefined) {
        return <h3>Failed to construct credential. Provided token is malformed.</h3>;
    }
    return <h3>Initializing...</h3>;

}

export default VideoComponent;
```

**Comment by jorgecolon413** [comment]
The past app does not include typescript which may be the reason why de adapter was not recognizing the locator. Manage to make the CallWithChatComposite work with an existing thread Id and a random generated group Id. 

Just copy the demo at https://azure.github.io/communication-ui-library/?path=/docs/composites-call-with-chat-jointeamsmeeting--join-teams-meeting 

and pass every required prop with the correct type. 
as such: 
```
const LOCATOR = { callLocator: { groupId: "d9fa1c0e-a6fc-11ed-afa1-0242ac120002" } as GroupCallLocator, chatThreadId: "19:Ei_vQErHBQe7DArbUuqR0Jubw_hx8xiXuFZelLxIxzo1@thread.v2" } as CallAndChatLocator
 ```
here is how a call the component: 
```
<div className='col-8'>
        <CallWithChatExperience userId={USER_ID} token={TOKEN} displayName={GROUP_ID} endpointUrl={ENDPOINT} locator={LOCATOR} />
      </div>
````
