### ISSUE TITLE
Build fails with "stringToUint8Array" is not exported by "@azure/core-util"

### ISSUE THREAD

**Issue by DercilioFontes** [Azure/communication-ui-library#3922]
**Describe the bug; what happened?**
The last version of "@azure/communication-react" "^1.11.0" is causing my React Vite project to fail.

```
"stringToUint8Array" is not exported by "node_modules/@azure/core-util/dist-esm/src/index.js", imported by "node_modules/@azure/core-rest-pipeline/dist-esm/src/policies/formDataPolicy.js".
file: /Users/trycycle-dercilio/repos.nosync/elm/node_modules/@azure/core-rest-pipeline/dist-esm/src/policies/formDataPolicy.js:3:9
1: // Copyright (c) Microsoft Corporation.
2: // Licensed under the MIT license.
3: import { stringToUint8Array } from "@azure/core-util";
            ^
4: import { createHttpHeaders } from "../httpHeaders";
5: /**
error during build:
RollupError: "stringToUint8Array" is not exported by "node_modules/@azure/core-util/dist-esm/src/index.js", imported by "node_modules/@azure/core-rest-pipeline/dist-esm/src/policies/formDataPolicy.js".
    at error (file:///Users/trycycle-dercilio/repos.nosync/elm/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at Module.error (file:///Users/trycycle-dercilio/repos.nosync/elm/node_modules/rollup/dist/es/shared/node-entry.js:12753:16)
    at Module.traceVariable (file:///Users/trycycle-dercilio/repos.nosync/elm/node_modules/rollup/dist/es/shared/node-entry.js:13190:29)
    at ModuleScope.findVariable (file:///Users/trycycle-dercilio/repos.nosync/elm/node_modules/rollup/dist/es/shared/node-entry.js:11607:39)
    at FunctionScope.findVariable (file:///Users/trycycle-dercilio/repos.nosync/elm/node_modules/rollup/dist/es/shared/node-entry.js:5911:38)
    at FunctionBodyScope.findVariable (file:///Users/trycycle-dercilio/repos.nosync/elm/node_modules/rollup/dist/es/shared/node-entry.js:5911:38)
    at BlockScope.findVariable (file:///Users/trycycle-dercilio/repos.nosync/elm/node_modules/rollup/dist/es/shared/node-entry.js:5911:38)
    at BlockScope.findVariable (file:///Users/trycycle-dercilio/repos.nosync/elm/node_modules/rollup/dist/es/shared/node-entry.js:5911:38)
    at BlockScope.findVariable (file:///Users/trycycle-dercilio/repos.nosync/elm/node_modules/rollup/dist/es/shared/node-entry.js:5911:38)
    at BlockScope.findVariable (file:///Users/trycycle-dercilio/repos.nosync/elm/node_modules/rollup/dist/es/shared/node-entry.js:5911:38)
```

**What are the steps to reproduce the issue?**
React Vite project with the latest versions and try to build it.

**What behavior did you expect?**
Build with no issues.

**If applicable, provide screenshots:**
<img width="1659" alt="Screenshot 2023-12-15 at 12 50 52 PM" src="https://github.com/Azure/communication-ui-library/assets/20172847/06bf088c-9c62-4b2e-86b7-80d58effa2cd">

**In what environment did you see the issue?**

    "@azure/communication-chat": "^1.4.0",
    "@azure/communication-common": "^2.3.0",
    "@azure/communication-react": "^1.11.0",
    "react": "^18.2.0",
    "typescript": "^5.3.3",
    "vite": "^5.0.10",

- OS & Device: macOS 14.1.2 (23B92)

**Is there any additional information?**
No

**Comment by mgamis-msft** [comment]
Hi @DercilioFontes, thank you for filing this issue.

Could you try adding the `"@azure/core-util": "1.5.0"` to your dependencies. We may have missed adding this to our peer dependencies list.

**Comment by DercilioFontes** [comment]
Hi @mgamis-msft,

Doing this in my `package.json` worked. Thanks.

```json
  "overrides": {
    "@azure/core-rest-pipeline": {
      "@azure/core-util": "^1.5.0"
    }
  }
```

**Comment by mgamis-msft** [comment]
Thanks for posting your solution @DercilioFontes. Closing this issue. Please let us know any other issues you find.
