### ISSUE TITLE
DeepNoiseSuppressionEffect not exported in 1.20.0

### ISSUE THREAD

**Issue by jgarplind** [Azure/communication-ui-library#5406]
**Describe the bug; what happened?**
Upgrading to 1.20.0, suddenly our builds fail. The logs look like this:
```
error during build:
../node_modules/.pnpm/@azure+communication-react@1.20.0_@azure+communication-calling-effects@1.0.1_@azure+communica_cr3t6mc7be2dvircsdjvuud634/node_modules/@azure/communication-react/dist/dist-esm/react-composites/src/composites/common/resolveDeepNoiseSuppressionDependency.js (10:9): "DeepNoiseSuppressionEffect" is not exported by "../node_modules/.pnpm/@azure+communication-calling-effects@1.0.1/node_modules/@azure/communication-calling-effects/dist-esm/sdk.bundle.js", imported by "../node_modules/.pnpm/@azure+communication-react@1.20.0_@azure+communication-calling-effects@1.0.1_@azure+communica_cr3t6mc7be2dvircsdjvuud634/node_modules/@azure/communication-react/dist/dist-esm/react-composites/src/composites/common/resolveDeepNoiseSuppressionDependency.js".
file: /home/runner/work/repo_name/repo_name/node_modules/.pnpm/@azure+communication-react@1.20.0_@azure+communication-calling-effects@1.0.1_@azure+communica_cr3t6mc7be2dvircsdjvuud634/node_modules/@azure/communication-react/dist/dist-esm/react-composites/src/composites/common/resolveDeepNoiseSuppressionDependency.js:10:9

 8:     });
 9: };
10: import { DeepNoiseSuppressionEffect } from '@azure/communication-calling-effects';
             ^
11: /**
12:  *

    at getRollupError (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at Module.error (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:14844:16)
    at Module.traceVariable (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:15291:29)
    at ModuleScope.findVariable (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:13192:39)
    at ReturnValueScope.findVariable (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:5221:38)
    at FunctionBodyScope.findVariable (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:5221:38)
    at ChildScope.findVariable (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:5221:38)
    at FunctionScope.findVariable (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:5221:38)
    at FunctionBodyScope.findVariable (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:5221:38)
    at Identifier.bind (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:4871:40)
    at NewExpression.bind (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:2836:23)
    at Property.bind (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:2836:23)
    at ObjectExpression.bind (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:2832:28)
    at VariableDeclarator.bind (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:2836:23)
    at VariableDeclaration.bind (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:2832:28)
    at BlockStatement.bind (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:2832:28)
    at FunctionExpression.bind (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:2836:23)
    at CallExpression.bind (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:2832:28)
    at CallExpression.bind (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:11148:15)
    at ArrowFunctionExpression.bind (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:2836:23)
    at VariableDeclarator.bind (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:2836:23)
    at VariableDeclaration.bind (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:2832:28)
    at ExportNamedDeclaration.bind (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:11597:27)
    at Program.bind (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:2832:28)
    at Module.bindReferences (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:14823:18)
    at Graph.sortModules (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:20225:20)
    at Graph.build (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:20128:14)
    at async file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:20772:13
    at async catchUnfinishedHookActions (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:20282:16)
    at async rollupInternal (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:20767:5)
    at async build (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/vite@5.4.10_@types+node@22.9.0_sass@1.80.6/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:65443:14)
    at async CAC.<anonymous> (file:///home/runner/work/repo_name/repo_name/node_modules/.pnpm/vite@5.4.10_@types+node@22.9.0_sass@1.80.6/node_modules/vite/dist/node/cli.js:828:5)
/home/runner/work/repo_name/repo_name/app_name:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @company_name/app_name@0.1.0 build: `vite build`
Exit status 1
Error: Process completed with exit code 1.
```

**What are the steps to reproduce the issue?**
Upgrade from 1.19 to 1.20. Build Vite app with pnpm.

**What behavior did you expect?**
No crash.

**If applicable, provide screenshots:**
See logs above.

**In what environment did you see the issue?**

- `@azure/communication-react` 1.20.0
- `@azure/communication-calling` 1.30.3
- `@azure/communication-chat` N/A

- OS & Device: Ubuntu (Github Actions). Windows 11 (local).
- Browser: N/A
- Browser Version: N/A

**Is there any additional information?**
1.19 builds just fine.

**Comment by JamesBurnside** [comment]
Hi @jgarplind, in your err log I see:

> `@azure+communication-calling-effects@1.0.1`

Deep noise suppression is only available in newer `@azure/communication-calling-effects` packages. Can you update to `@azure/communication-calling-effects@1.1.1` and check back in if you still see the error?

**Comment by jgarplind** [comment]
Sure, I'll try that and report back, thanks!

However, I never explicitly installed that package, so it seems that something with the dependency specification is/was not fully in sync on your end, right?

**Comment by JamesBurnside** [comment]
The `package.json` in the `@azure/communication-react` npm package specifies the appropriate `peerDependency` packages (for which we have `react`, `@azure/communication-calling`, `@azure/communication-calling-effects`, `@azure/communication-chat`). When you update to the latest `@azure/communication-react` your package manager (npm/yarn/pnpm) should either install the latest peer dependency or flag that it needs installed.

Out of interest what package manager and version do you have?

**Comment by jgarplind** [comment]
pnpm 9 something, I'll have a proper look in the morning over here in Europe.

**Comment by jgarplind** [comment]
I'm running pnpm 9.3.

I can see correctly specified `peerDependencies` (it was raised from 1.0.1 to 1.1.1 between 1.19 and 1.20).

But still, the end result in the lock file is this:

```
'@azure/communication-react@1.20.0(@azure/communication-calling-effects@1.0.1)(@azure/communication-calling@1.30.3)(@azure/communication-chat@1.5.2)(@types/react-dom@18.3.1)(@types/react@18.3.12)(react-dom@18.3.1(react@18.3.1))(react@18.3.1)(scheduler@0.23.2)':
    dependencies:
      '@azure/communication-calling-effects': 1.0.1
      ...
```

💯 I actually got it working now, resorting to the classic trick of removing both the lockfile and every `node_modules` folder.

I'm not sufficiently well versed in `pnpm` to know why that might be.

Thanks for sharing your insights, it has been very helpful.
